### ISSUE TITLE
How to send commands to wifi box?

### ISSUE THREAD

**Issue by webfrank** [mwittig/node-milight-promise#16]
I have a V6 WiFi iBox with light and no other bulbs at the moment, but I cannot find a way to send commands to the bridge itself.

**Comment by mwittig** [comment]
See https://github.com/mwittig/node-milight-promise/blob/master/examples/example-bridge-v6.js which is an example on how to control the bridge light. Instead of providing the global broadcast address which is the default, you should provide the IP address of the Milight Controller for unicast mode. Don't use the global broadcast address on Windows as this may give unexpected results.

**Comment by mwittig** [comment]
I think the question has been answered. Please re-open if you want to follow-up on this
